version: "3.7"

services:

  flask:
    build: ./threat-net
    container_name: flask
    restart: always
    environment:
      - APP_NAME=run.py
    
      # not for outside! Expose internally
    expose:
      - 8080